{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kffmod",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kffmod-4.5.0.jar",
          "url": "kffmod-4.5.0.jar",
          "size": 69751,
          "sha512": "b35831d705733239820115863d7698c5b798dc5bb206003bfa2f5f9a0d10dbb889c001ab9586dac6d8d87c73e5f5dbb01b062ee2662f0bf104cf48a2efa0f316",
          "sha256": "0252a70a40e82e6c0c23ec860b8179334cca2e3a47169a030353d34aa199aa21",
          "sha1": "0642530c333231026dd42e83865b0e0f9a35c373",
          "md5": "e25b87c0a1bb6305d5b2b9178456a215"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kffmod-4.5.0.jar",
          "url": "kffmod-4.5.0.jar",
          "size": 69751,
          "sha512": "b35831d705733239820115863d7698c5b798dc5bb206003bfa2f5f9a0d10dbb889c001ab9586dac6d8d87c73e5f5dbb01b062ee2662f0bf104cf48a2efa0f316",
          "sha256": "0252a70a40e82e6c0c23ec860b8179334cca2e3a47169a030353d34aa199aa21",
          "sha1": "0642530c333231026dd42e83865b0e0f9a35c373",
          "md5": "e25b87c0a1bb6305d5b2b9178456a215"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kffmod-4.5.0-sources.jar",
          "url": "kffmod-4.5.0-sources.jar",
          "size": 69094,
          "sha512": "7594e2a49c37a75bcaaf17431200cf563fe406a8090af85a74cc90576b06cab48c7190fb1cb6c0ec22304edeeae7cf35ab73ed80cc60f878d639a335a7ad7eab",
          "sha256": "6646d1fb71946c6a9c360af36a1c230f410c721069a9b740b16972eff0a2a8a0",
          "sha1": "597aa8ff7ddf2fd5421868acd1dea5acf2bdbf2d",
          "md5": "7321c3b0624f60d2a11269fe5759dfdc"
        }
      ]
    }
  ]
}
