{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "3.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-3.9.1.jar",
          "url": "kfflib-3.9.1.jar",
          "size": 24998,
          "sha512": "6b6551049f0389ea4f0d797ec9dbe9acaa744e619cd1eca9f750de31334ae809de62a7da1b908d528fb400ec00403894acdad364de20b3a467577942f797dc48",
          "sha256": "a56f21e2ab53d72dbb10e47184521e36296a0668d2827c324ccb0affaa087b9b",
          "sha1": "7b5907087dcdf25053200258a6ffa8f784766236",
          "md5": "b2cfc24819ba8de330ee23fe70be1f73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-3.9.1.jar",
          "url": "kfflib-3.9.1.jar",
          "size": 24998,
          "sha512": "6b6551049f0389ea4f0d797ec9dbe9acaa744e619cd1eca9f750de31334ae809de62a7da1b908d528fb400ec00403894acdad364de20b3a467577942f797dc48",
          "sha256": "a56f21e2ab53d72dbb10e47184521e36296a0668d2827c324ccb0affaa087b9b",
          "sha1": "7b5907087dcdf25053200258a6ffa8f784766236",
          "md5": "b2cfc24819ba8de330ee23fe70be1f73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-3.9.1-sources.jar",
          "url": "kfflib-3.9.1-sources.jar",
          "size": 9177,
          "sha512": "6eaa1b40bda4164237080a9926ed866280313443fb2302c5eee1e04c7f94c7015a8167c305af7645c4a48b54c46adf07b3d47ff8c352e325983dcd172f28d272",
          "sha256": "6daadad2dfa10922bdf7b5394e60150fa412d4d9223016ff9edf30155769dd4b",
          "sha1": "85242543e68081b0cb96b856de432d0bcfe0c6e0",
          "md5": "3d4634a8c3405a5b4790ce39f3e41e26"
        }
      ]
    }
  ]
}
