{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kffmod",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kffmod-4.7.0.jar",
          "url": "kffmod-4.7.0.jar",
          "size": 69743,
          "sha512": "e071c7c060208a73e172d8360e70383dd854718b6ce25962f782da638d3730cb1848eca641de4ecda66455f29dc43a471ef6c364377e4129c1fafedb998fd67b",
          "sha256": "741fb52ef20213e4f6bd43c5b5f5b73d7e349229254153a832603cfeb5a3460d",
          "sha1": "a9f3d45aa7682ccd727e95c292b1e8a5fbe9fe1e",
          "md5": "33d805d74a435202ed4fdc1c72ece250"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kffmod-4.7.0.jar",
          "url": "kffmod-4.7.0.jar",
          "size": 69743,
          "sha512": "e071c7c060208a73e172d8360e70383dd854718b6ce25962f782da638d3730cb1848eca641de4ecda66455f29dc43a471ef6c364377e4129c1fafedb998fd67b",
          "sha256": "741fb52ef20213e4f6bd43c5b5f5b73d7e349229254153a832603cfeb5a3460d",
          "sha1": "a9f3d45aa7682ccd727e95c292b1e8a5fbe9fe1e",
          "md5": "33d805d74a435202ed4fdc1c72ece250"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kffmod-4.7.0-sources.jar",
          "url": "kffmod-4.7.0-sources.jar",
          "size": 69085,
          "sha512": "c081f3be5554262ae79f5087a80322e7a4a419906edfb32d96dfdd576d3a9c6f0abd636f8896f5bee6fc53ee9c63db248d12bf24241fcfcfcae680fe5bb9a814",
          "sha256": "112ed721dc0eb0d4112e9eb5c712d169d1ba37e4172cf5a2191078bcb34dc298",
          "sha1": "1c02e72b9114872bb04459ee1289de702def5494",
          "md5": "0ba70d6761bcc23e65a09720e1034fdb"
        }
      ]
    }
  ]
}
