{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.5.0.jar",
          "url": "kfflib-4.5.0.jar",
          "size": 41782,
          "sha512": "f1ee2f00a07321781c3ad912a85da0bc6d892247405e20adeeea15756ea97c4bcb8d978cafafda554769c3e34acc0bc30391ab746284a0c24ab91f1632ef3852",
          "sha256": "035f8fa62184d6ca1d37e594cb55d3c325707dd56be4cb377362909331367cc9",
          "sha1": "bc37ba997cec823d1aff98f294eaba68906efe1a",
          "md5": "a692127169eff5a330be2f417d361232"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.5.0.jar",
          "url": "kfflib-4.5.0.jar",
          "size": 41782,
          "sha512": "f1ee2f00a07321781c3ad912a85da0bc6d892247405e20adeeea15756ea97c4bcb8d978cafafda554769c3e34acc0bc30391ab746284a0c24ab91f1632ef3852",
          "sha256": "035f8fa62184d6ca1d37e594cb55d3c325707dd56be4cb377362909331367cc9",
          "sha1": "bc37ba997cec823d1aff98f294eaba68906efe1a",
          "md5": "a692127169eff5a330be2f417d361232"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.5.0-sources.jar",
          "url": "kfflib-4.5.0-sources.jar",
          "size": 12566,
          "sha512": "5654333144be187e60431936e702e4d83217b66884d51ed96dfbf1c3d83435edfc7f24aa76fe9dfadc25bc63c89ad39a100670f99c67c40abf075ba0223ae161",
          "sha256": "9770f12741e9b937f74082a353758624da69d341e53f0bc694c0eeb6bf3cf88e",
          "sha1": "18a44feb6923d6b71dc5835ba3633ad3df25185a",
          "md5": "65defecdd957bc3ba97b0674673be6bc"
        }
      ]
    }
  ]
}
