{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.5.0.jar",
          "url": "kfflib-4.5.0.jar",
          "size": 41782,
          "sha512": "aa666840a24347e999119234996aa91216b394ffad026a77e99885774245d6474182ed583710617b018916b8f407f296cdf084a7f912bfca85e150d3fd7695fe",
          "sha256": "f701f0a980ca5726ea7d3f4a8431c4741f82f96e130be08f4b78c8915146523e",
          "sha1": "73d2aa29ef53d41af2ad7b2c2ca3af150660bc59",
          "md5": "404cba2974f8ef41617115cb4b01e7eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.5.0.jar",
          "url": "kfflib-4.5.0.jar",
          "size": 41782,
          "sha512": "aa666840a24347e999119234996aa91216b394ffad026a77e99885774245d6474182ed583710617b018916b8f407f296cdf084a7f912bfca85e150d3fd7695fe",
          "sha256": "f701f0a980ca5726ea7d3f4a8431c4741f82f96e130be08f4b78c8915146523e",
          "sha1": "73d2aa29ef53d41af2ad7b2c2ca3af150660bc59",
          "md5": "404cba2974f8ef41617115cb4b01e7eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.5.0-sources.jar",
          "url": "kfflib-4.5.0-sources.jar",
          "size": 12566,
          "sha512": "50c61b3972be85bf992fa388d379f81ea16b0bc4634e2c2dba729f125e6d765de39d474d6233955a30efcba053d535a3a291f62fd06ebe43d0643055c6e0c345",
          "sha256": "3b6de3c4170065a6090ecc9d2cf228e59aee3a29dbce039549d2e418d22459b6",
          "sha1": "04726f42198711c7cf1d88a9482a2db59bf8d185",
          "md5": "d3f14f5d41c2fd877b0cfc167dc2d449"
        }
      ]
    }
  ]
}
