{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-4.7.0.jar",
          "url": "kfflib-neoforge-4.7.0.jar",
          "size": 40635,
          "sha512": "51dcad10df024a9d2656c106605b36badb2db9e3b82073ce9841b5f3401aba4625b414bf3a4a7cf0d88594614dab4112b798b61c0b019e7536ddf10ae6324c3c",
          "sha256": "bcd060180dce85c5484bff9d2cea16ea578619492e868330dd3879754a4375d2",
          "sha1": "7f360cba855dafb40bb21fd4be0577d2a106f430",
          "md5": "df477afa51f21ac3d7a5ffa5a4437b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-4.7.0.jar",
          "url": "kfflib-neoforge-4.7.0.jar",
          "size": 40635,
          "sha512": "51dcad10df024a9d2656c106605b36badb2db9e3b82073ce9841b5f3401aba4625b414bf3a4a7cf0d88594614dab4112b798b61c0b019e7536ddf10ae6324c3c",
          "sha256": "bcd060180dce85c5484bff9d2cea16ea578619492e868330dd3879754a4375d2",
          "sha1": "7f360cba855dafb40bb21fd4be0577d2a106f430",
          "md5": "df477afa51f21ac3d7a5ffa5a4437b18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-4.7.0-sources.jar",
          "url": "kfflib-neoforge-4.7.0-sources.jar",
          "size": 12637,
          "sha512": "326c980de96cee68334ff42fffe1fc1c4fa01b0ddc03a0cf7f5e84b7fa488cc0390b2a6e5a9293f64dfc2c1f7f4326dd3987bf69ab2f400aa21d1eb9e8b8a887",
          "sha256": "cf978a536575222814522b09c24bb3ba3d26de9a6fae0b122b2c9780037d425b",
          "sha1": "2fde83dd59e71ee114763819e77c5b1512dc01a0",
          "md5": "bd791538d4169066f19c255c8d7d228e"
        }
      ]
    }
  ]
}
