[versions]
kotlin = "2.4.10"
coroutines = "1.11.0"
serialization = "1.11.0"
neogradle = "7.0.138"
neoforge = "20.4.22-beta"
forgegradle = "6.0.25"
minotaur = "2.8.7"
cursegradle = "1.4.0"

# https://github.com/JetBrains/kotlin
# https://github.com/Kotlin/kotlinx.coroutines
# https://github.com/Kotlin/kotlinx.serialization
[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "com.matthewprenger.cursegradle", version.ref = "cursegradle" }
