{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "KotlinForForge",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "4.5.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinForForge-4.5.0-all.jar",
          "url": "KotlinForForge-4.5.0-all.jar",
          "size": 7505636,
          "sha512": "ba1f7f6cf6f202de876899dceb1493e3f82a9fbaaa2c0eb4a629e944117b0a17a00c070ceda1c802e29a0197a8a6b58ac1b47c4d3833f380a37f7095dace4d7d",
          "sha256": "5e6bfbfd2a0e59a6d5a34f6356aae998ad728af5f9730ca033c670121d6791ea",
          "sha1": "6051235d8d59d861ddd925e4f896c87b7ba4095b",
          "md5": "4f8b6ed60debb90ca58eff9ab9f3d229"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KotlinForForge-4.5.0-sources.jar",
          "url": "KotlinForForge-4.5.0-sources.jar",
          "size": 261,
          "sha512": "a68f95e7c0a58791f28cd5f0f064c86dad0620ec64d95096b8e0a2fd9cd7cfbbfef69b9d14d0e5598b9bddf195e1f32669545ca51d10b414e94ad19cb0fe80ed",
          "sha256": "60f865e89828e6dcda281ca11d213617d2d2e0dc302af57ac7985dd8819e3156",
          "sha1": "511570a8952636602cf5f6c70cc113735d591d2a",
          "md5": "0a1885d5fd4f2e37dbeca9e8a3f75309"
        }
      ]
    }
  ]
}
