{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "4.5.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinforforge-4.5.0-all.jar",
          "url": "kotlinforforge-4.5.0-all.jar",
          "size": 7505630,
          "sha512": "93041b44703908b966128fd765ce0f5aef2c091533df0a27f883fc89def0f853ff7223382699d68e24852b5041783d3473031c0007b19c45573134b3eba8504c",
          "sha256": "7cdeefa76a7c38f1ba8b1f59b7d3ed89c97487a5fbf0dd8c690f8567b46f97f9",
          "sha1": "d14ac5214ddbb660572670c3a50eff5a0dc5335c",
          "md5": "c4d70149571f53707114876e1331e695"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinforforge-4.5.0-sources.jar",
          "url": "kotlinforforge-4.5.0-sources.jar",
          "size": 261,
          "sha512": "8f9c91f1a2319df92a4fe43bfb78358ec5707f718d732ac3027ee8396b92b1e2b45542b3f3e954ec4c7900aec0be8fcfd57da616610cdb962f52a18938e013ea",
          "sha256": "813a0fe98649579fe8df669cb3a4fba448206160816985b133761446a72e96b9",
          "sha1": "199fa0937c1674c8599284f5b73e53a49164d543",
          "md5": "5248dd8b97459ea26e99e75310b2014f"
        }
      ]
    }
  ]
}
