{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-4.12.0.jar",
          "url": "kfflib-neoforge-4.12.0.jar",
          "size": 39345,
          "sha512": "5c9989331c13367b191a45ce0471f9ae3a93e1f4899a1fa4eece2003c0b21c57d1606f4ae64c16b8a83ca94702fccdd0f7972e5a86d854c60d894bb4f7ac81b5",
          "sha256": "bf23183d17ce2dce23c67d04a6f1d830c17e2cb76e28fb49b2c16c6a295381ef",
          "sha1": "6f3171a3d27862013410b3b54851b5b7ce90e55f",
          "md5": "5da8abaf021d1fe0f21495361bdbe71c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-4.12.0.jar",
          "url": "kfflib-neoforge-4.12.0.jar",
          "size": 39345,
          "sha512": "5c9989331c13367b191a45ce0471f9ae3a93e1f4899a1fa4eece2003c0b21c57d1606f4ae64c16b8a83ca94702fccdd0f7972e5a86d854c60d894bb4f7ac81b5",
          "sha256": "bf23183d17ce2dce23c67d04a6f1d830c17e2cb76e28fb49b2c16c6a295381ef",
          "sha1": "6f3171a3d27862013410b3b54851b5b7ce90e55f",
          "md5": "5da8abaf021d1fe0f21495361bdbe71c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-4.12.0-sources.jar",
          "url": "kfflib-neoforge-4.12.0-sources.jar",
          "size": 12131,
          "sha512": "89eef6613b8c82bc285d472c2e1869f00a44cad80396bad64b417a53e29d848ea0cd44aec79476dbe88586702fe82e80ac21cec2a722935ded3f4695e912fb6c",
          "sha256": "b2e71cbd106efed3b28e1d16da329495c7760d3e0c78dfcb844145de69e38fea",
          "sha1": "394dbbb89e5acfa522608fe74143ab21af23af4e",
          "md5": "01d487f257fd566f2ed74fe63aeccc38"
        }
      ]
    }
  ]
}
