{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "4.7.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinforforge-4.7.0-all.jar",
          "url": "kotlinforforge-4.7.0-all.jar",
          "size": 7292509,
          "sha512": "c8f189de2d8e5de929e8a3e7c554bdbb800b2513ff9a58ac0528810575691f011665d190ee309a5a603b6838f4071ef06ac4e031ace6409ad4ebff403e54ad50",
          "sha256": "932a3d0a9f6a5d641068db1f92faaf8e516542bebd86274930c81a0422e572ba",
          "sha1": "1de38e2649e7952bd0a7774a181feb54994a8e39",
          "md5": "f45e318d561953b2b31c1a0aad0ad80d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinforforge-4.7.0-sources.jar",
          "url": "kotlinforforge-4.7.0-sources.jar",
          "size": 261,
          "sha512": "360230a8b2ee8ca2388b0edb4574ce0623c8a1197b9ca1031fd35ab7a274b4fdf26d577043cb02fa9bdb66d9b77c462507ce841621d3e99b0360c607a5f09fac",
          "sha256": "91bb4e2cdfaa0aa668f2eaf722f8eb5c655ed3615d28965e3224191f77375944",
          "sha1": "8e49c3dc90eb872ed6e21c6bed9d8eefc94bef75",
          "md5": "c2d31918e79cc60e8c53b896b59e45ec"
        }
      ]
    }
  ]
}
