{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-4.5.0.jar",
          "url": "kfflang-4.5.0.jar",
          "size": 23244,
          "sha512": "11e23f433783f88febbf676c4d4c19fa7fc070a225e9065dbf2db031c7501fb42c6f7f7ec30f21cf1afe6dd9f6056659969fac710d6d80e012d02ce339629ebe",
          "sha256": "21be2c4c31851974d4a96e95a8b20501c28b01a06f8b900a612a0b7582c84c9e",
          "sha1": "d458a1ac045cf581318ac9e0d85b2200e0c678b3",
          "md5": "22ced2ac1cdcd64ac0d9c264cce2af74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-4.5.0.jar",
          "url": "kfflang-4.5.0.jar",
          "size": 23244,
          "sha512": "11e23f433783f88febbf676c4d4c19fa7fc070a225e9065dbf2db031c7501fb42c6f7f7ec30f21cf1afe6dd9f6056659969fac710d6d80e012d02ce339629ebe",
          "sha256": "21be2c4c31851974d4a96e95a8b20501c28b01a06f8b900a612a0b7582c84c9e",
          "sha1": "d458a1ac045cf581318ac9e0d85b2200e0c678b3",
          "md5": "22ced2ac1cdcd64ac0d9c264cce2af74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-4.5.0-sources.jar",
          "url": "kfflang-4.5.0-sources.jar",
          "size": 7692,
          "sha512": "dd87a505bff192a7023185a246f6eb75c8f7ee44c86c5496fe95e389e5c2008638b0ac7ab564a93f47c4ff361147df1e8a5a07b5f4c18dd1f7a032619e1a74df",
          "sha256": "d77e9847efc93d1c828db61f159c7bf2e32c395d3baa3f0f140b6032bf1a60e7",
          "sha1": "6ca7e18cc3f834d248f91f2841f7ab900b12fe51",
          "md5": "792cd3c904dbcd6ea28bec7107cba5b9"
        }
      ]
    }
  ]
}
