{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-4.7.0.jar",
          "url": "kfflang-4.7.0.jar",
          "size": 23264,
          "sha512": "cd2fd9b9669e62e85a931b0f6e4bc13a872812d03e5cfcdfaa7d45393f8c06032bc206dc81d19e0eb4496ec7186c9cc2c05f73afe7c8046dc1451548a279f311",
          "sha256": "33d00df3c2183e666b9d3dd95c555eddd52d8db5107e7c313cc7cbf597ecff88",
          "sha1": "93cedc406dbd0843b3451f8d9d25741d79ddaefa",
          "md5": "5246c0c103525d84a6fb57e3ae2c920e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-4.7.0.jar",
          "url": "kfflang-4.7.0.jar",
          "size": 23264,
          "sha512": "cd2fd9b9669e62e85a931b0f6e4bc13a872812d03e5cfcdfaa7d45393f8c06032bc206dc81d19e0eb4496ec7186c9cc2c05f73afe7c8046dc1451548a279f311",
          "sha256": "33d00df3c2183e666b9d3dd95c555eddd52d8db5107e7c313cc7cbf597ecff88",
          "sha1": "93cedc406dbd0843b3451f8d9d25741d79ddaefa",
          "md5": "5246c0c103525d84a6fb57e3ae2c920e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-4.7.0-sources.jar",
          "url": "kfflang-4.7.0-sources.jar",
          "size": 7336,
          "sha512": "f20ceb073fd075d7f07f52992b33d10d57e54004a4663765794650ce5f9650c568425a9c1f720132396e5e028e7515e7686e0834439674cfce10dd6e4471b716",
          "sha256": "e52376a1e406e005c7ee85c01b023e0392057ad9464b4bda848408fb75cce084",
          "sha1": "61c1bb955d6f9c738e0e5174b5d1b0cfcbb1d308",
          "md5": "769c14accf7182201e1bcc2d06ff7343"
        }
      ]
    }
  ]
}
