{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-4.7.0.jar",
          "url": "kfflang-4.7.0.jar",
          "size": 23264,
          "sha512": "851f1b30efdb73a885c9ec576ddbf4b45c13148a4b1938aba712f66630d125113451adb0b3c44136c53c66ee768d8f20e684bc67a6f9a29b3bbf0d52f51a513b",
          "sha256": "8ce027efe9508b42feba20a3e8cf88775e42818edf605dd19026e17c3c9f4d80",
          "sha1": "2eea7c8f4374edcfdc81e9bf6c721eba1abb3de5",
          "md5": "96d3db478cee35dee8d45ba73345aecc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-4.7.0.jar",
          "url": "kfflang-4.7.0.jar",
          "size": 23264,
          "sha512": "851f1b30efdb73a885c9ec576ddbf4b45c13148a4b1938aba712f66630d125113451adb0b3c44136c53c66ee768d8f20e684bc67a6f9a29b3bbf0d52f51a513b",
          "sha256": "8ce027efe9508b42feba20a3e8cf88775e42818edf605dd19026e17c3c9f4d80",
          "sha1": "2eea7c8f4374edcfdc81e9bf6c721eba1abb3de5",
          "md5": "96d3db478cee35dee8d45ba73345aecc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-4.7.0-sources.jar",
          "url": "kfflang-4.7.0-sources.jar",
          "size": 7336,
          "sha512": "b8ee0fb2b3414fd838b1585ab8561215286842b84dad80795a7a4ca345916230a3675d3efe83345a6afa0996fb177925b83eb203106ec6aa57d60f327cf879bb",
          "sha256": "101e1b2c786995672cde4f7582bb62564e5b2f7c689ce1090f8982955cbd9ecf",
          "sha1": "801e532c9d9c4817b530561ae8c06e820fd68977",
          "md5": "bee4a9c3392e8b43a50e416942675804"
        }
      ]
    }
  ]
}
