{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge-neoforge",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "4.7.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinforforge-neoforge-4.7.0-all.jar",
          "url": "kotlinforforge-neoforge-4.7.0-all.jar",
          "size": 7654114,
          "sha512": "407cd1dd594fb9990876782c034d7ba469c9dace0983404c472ceb90a301f0176c8feb9c80471ecae5d5ad062b8d7cf7ad2ae2ceb68a7669911855bd1c7bf4a1",
          "sha256": "de706e6fd19b96462c8d9a94ce7af4f7f063f6adaa1d34be904b45e95cf33514",
          "sha1": "75e9bf0470417c903667b70f9a5e203ed4e8ae26",
          "md5": "223ac504221032533bfd1fe42f89d9d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinforforge-neoforge-4.7.0-sources.jar",
          "url": "kotlinforforge-neoforge-4.7.0-sources.jar",
          "size": 261,
          "sha512": "d7ec7451bfb1c486c1f002be97a13db2beba8f0f744414d3f631d7b42059e5b0a55f2e8179432e86fd3d8e3fff3ead355b121e367c3777a2f1296a8ef67e7774",
          "sha256": "cc1957689a564bcafcb7d3931f39e08c89507eaec2fbb29663e3cfcb7aec695f",
          "sha1": "572b0febeac240e34d45cd3755c3805bd8bec2f4",
          "md5": "ba907d5cae65926238239d15ea8d2bb6"
        }
      ]
    }
  ]
}
