{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.12.0.jar",
          "url": "kfflib-4.12.0.jar",
          "size": 41592,
          "sha512": "67dadb09a9773065b09e250f66bbdb3dd27e7aa33c10aab53b27344058e0ba4f70ecc364dcad0eb6d7efaeea91322e08777de0189ad64e333e72fec69785429a",
          "sha256": "b606e3f41bf389b6bfdb3d0a908ec90b78d6dd7ede284e3c5bef44bd0c0f280d",
          "sha1": "575586b24c7af5c82ee256be3014bc49474e1a62",
          "md5": "82d3b5da5b2643ccf458f7006b97e26e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.12.0.jar",
          "url": "kfflib-4.12.0.jar",
          "size": 41592,
          "sha512": "67dadb09a9773065b09e250f66bbdb3dd27e7aa33c10aab53b27344058e0ba4f70ecc364dcad0eb6d7efaeea91322e08777de0189ad64e333e72fec69785429a",
          "sha256": "b606e3f41bf389b6bfdb3d0a908ec90b78d6dd7ede284e3c5bef44bd0c0f280d",
          "sha1": "575586b24c7af5c82ee256be3014bc49474e1a62",
          "md5": "82d3b5da5b2643ccf458f7006b97e26e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.12.0-sources.jar",
          "url": "kfflib-4.12.0-sources.jar",
          "size": 12443,
          "sha512": "e841a6f60f59b9dca46f3c08bb075f30270a5f0e8c96ad6e1b80e5df173ba2625ef1f552d201719cc3c457ed7d9f0fec6913e3c8a28984c15d7cdf336f1e6961",
          "sha256": "03a088dae3ea303daf0e24cfc5dc68e4c4d1cce755686142e795c4c02f1feaa6",
          "sha1": "018f454894ff1ee11d9dce95c10c232ca9987782",
          "md5": "7da453b0d651525fa4756f5f5d0ad592"
        }
      ]
    }
  ]
}
