{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "3.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-3.11.0.jar",
          "url": "kfflib-3.11.0.jar",
          "size": 26649,
          "sha512": "76df73301752559ffb8d9d5de48dceae0ac669429bbc5f138e25fe787b38d21771bae14439cb98aa04e5273732ee7ee9cf31e0a6152559beda6dac8954c85965",
          "sha256": "ea7979f5d32eb8942991a813e4deca6f5b4f009e91f7086fd64fb749ca79d49e",
          "sha1": "e2b50c7fe4f8a0b275dc9cf498e8f371c72b8b04",
          "md5": "5ae482f7e2043be4c40f628d63a14e5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-3.11.0.jar",
          "url": "kfflib-3.11.0.jar",
          "size": 26649,
          "sha512": "76df73301752559ffb8d9d5de48dceae0ac669429bbc5f138e25fe787b38d21771bae14439cb98aa04e5273732ee7ee9cf31e0a6152559beda6dac8954c85965",
          "sha256": "ea7979f5d32eb8942991a813e4deca6f5b4f009e91f7086fd64fb749ca79d49e",
          "sha1": "e2b50c7fe4f8a0b275dc9cf498e8f371c72b8b04",
          "md5": "5ae482f7e2043be4c40f628d63a14e5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-3.11.0-sources.jar",
          "url": "kfflib-3.11.0-sources.jar",
          "size": 9685,
          "sha512": "e92319c17e8fbec0dcad9fde656c266db2ee3265218c790c94daa93abe2bc74b4b50103e7ca707b69a3eb337436b640b04d6752bdc4d74604403449efdd58df9",
          "sha256": "9940a414767ec7e6828024ddbfe90338c39c7670ca3b2ebae65a6da991451803",
          "sha1": "87aab0d245e3a34daa8a4a41d95dd64e95fa947d",
          "md5": "44ee73d17032714739f9094d490c4b73"
        }
      ]
    }
  ]
}
