{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.8.0.jar",
          "url": "kfflib-4.8.0.jar",
          "size": 41779,
          "sha512": "d1e7f0aa9f8a314d59afb2c7870c7c63dc1a202fbf841d0ee40321f97487b87759b253d564a80fe47d02a1f6793363b18072ea73ec365788e40b8585b3684f27",
          "sha256": "dadcab50e78283d2de0e1e9c9bf1845e5f0ba37c53ce940f819af02dffc1318c",
          "sha1": "1c6da907b25ecd11ce20e63ee917580f025d93c4",
          "md5": "d833fd443534f89dded126e91f284f7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.8.0.jar",
          "url": "kfflib-4.8.0.jar",
          "size": 41779,
          "sha512": "d1e7f0aa9f8a314d59afb2c7870c7c63dc1a202fbf841d0ee40321f97487b87759b253d564a80fe47d02a1f6793363b18072ea73ec365788e40b8585b3684f27",
          "sha256": "dadcab50e78283d2de0e1e9c9bf1845e5f0ba37c53ce940f819af02dffc1318c",
          "sha1": "1c6da907b25ecd11ce20e63ee917580f025d93c4",
          "md5": "d833fd443534f89dded126e91f284f7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.8.0-sources.jar",
          "url": "kfflib-4.8.0-sources.jar",
          "size": 12563,
          "sha512": "f88971257544335115a6c6f81dc8367a535d6b470387e001c9da38e571692bfd0d58e0623fbe743a3935e286346a99b677641e09cb69516367b32c0c762f503d",
          "sha256": "d6fa2af64fb787948a30bd9f06c2a388174755db672d61b02cd4e2c1d970289f",
          "sha1": "d3a2c0acbb8d1c6c7e0a7683584eb8a88b5cdd46",
          "md5": "4bf726b17a763ce437d84a431eb7e39f"
        }
      ]
    }
  ]
}
