{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.6.0.jar",
          "url": "kfflib-4.6.0.jar",
          "size": 41779,
          "sha512": "ea67ccffb1e034b200790692eaa860c611a776e68034c2050d6c2c84b792b97ae0e8d726393b4b9c083f8b7acd98b99efcada36728e47c321ac019e77c8fe604",
          "sha256": "8e724bd0a2ae431388919129a3b643d1a551f61f0e08fc654febf53ff06ff05e",
          "sha1": "dc232b5698de30113a8ff82d192c321a5ccc7c9c",
          "md5": "17dc584cf1e51a27ff9b641ee285021a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.6.0.jar",
          "url": "kfflib-4.6.0.jar",
          "size": 41779,
          "sha512": "ea67ccffb1e034b200790692eaa860c611a776e68034c2050d6c2c84b792b97ae0e8d726393b4b9c083f8b7acd98b99efcada36728e47c321ac019e77c8fe604",
          "sha256": "8e724bd0a2ae431388919129a3b643d1a551f61f0e08fc654febf53ff06ff05e",
          "sha1": "dc232b5698de30113a8ff82d192c321a5ccc7c9c",
          "md5": "17dc584cf1e51a27ff9b641ee285021a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.6.0-sources.jar",
          "url": "kfflib-4.6.0-sources.jar",
          "size": 12566,
          "sha512": "2e12fb041caa0e3087502168938ebd021ec251c7495f8e43e7469b80b270fc369207a101dd026cd1b3f9456d32a83dafdf04932799271991993f67b47e0d1136",
          "sha256": "7ce8e710eb25572506e9ae8c8a9f8d0328ac06901b19efee318d3e5240cd46ea",
          "sha1": "50e12db563745690752d5e403e99bfc5b94cf371",
          "md5": "4d52c67d14a22534fcec5513b9aadad3"
        }
      ]
    }
  ]
}
