{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang-neoforge",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-4.12.0.jar",
          "url": "kfflang-neoforge-4.12.0.jar",
          "size": 21803,
          "sha512": "aae1fa43a0d48b350bca3faf319aa9ca01573dd4ee25a769c114454f4f39b463f8411f87672c34f06e0a1554aca0f7ad497efe4f7fc8e068c52db2ed7b014e6c",
          "sha256": "c97099681f6e735ab86758aed49c2d215e7e16a58225caf8f5c26f7e4a79205a",
          "sha1": "08e4a08a492b97af8f12961891f49f68ff5ee4e7",
          "md5": "7d35a4f47d665ab1df06b5e8be852d9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-4.12.0.jar",
          "url": "kfflang-neoforge-4.12.0.jar",
          "size": 21803,
          "sha512": "aae1fa43a0d48b350bca3faf319aa9ca01573dd4ee25a769c114454f4f39b463f8411f87672c34f06e0a1554aca0f7ad497efe4f7fc8e068c52db2ed7b014e6c",
          "sha256": "c97099681f6e735ab86758aed49c2d215e7e16a58225caf8f5c26f7e4a79205a",
          "sha1": "08e4a08a492b97af8f12961891f49f68ff5ee4e7",
          "md5": "7d35a4f47d665ab1df06b5e8be852d9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-neoforge-4.12.0-sources.jar",
          "url": "kfflang-neoforge-4.12.0-sources.jar",
          "size": 7044,
          "sha512": "613c29daa25773e9593444fadec50b9694145345879b21005c3f53ca9215195dff5dc80790cc64dbddcc61b2bdcd77cdabf217551a0d16b4d725cc4598b77c50",
          "sha256": "3e6342e6be064a2f89cbba5a7a13d27f298481754745e6d684b693ee932e3819",
          "sha1": "3b4b6ed85835b08368a53b2f579e112e11ef6bbe",
          "md5": "4b2355d1bb46a66ad28ed68c89b7e91e"
        }
      ]
    }
  ]
}
