{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang-neoforge",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-4.7.0.jar",
          "url": "kfflang-neoforge-4.7.0.jar",
          "size": 22073,
          "sha512": "b527d7af9c5b3e03402df209601615228eb30203de578a2a91ce14aea4a57b71d3350ed3e278e74a6085d8f70f606cb5afbd67022ef60671a1ba197a74b65c4e",
          "sha256": "5e685aa01e52b8c0abfc3854618deff97fc6d6107c54000475f9675b28ffffb4",
          "sha1": "c0f30c236239ed85c50322ead36803b391b6e780",
          "md5": "4c441d32d1239df42bc77d3a03bdb828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-4.7.0.jar",
          "url": "kfflang-neoforge-4.7.0.jar",
          "size": 22073,
          "sha512": "b527d7af9c5b3e03402df209601615228eb30203de578a2a91ce14aea4a57b71d3350ed3e278e74a6085d8f70f606cb5afbd67022ef60671a1ba197a74b65c4e",
          "sha256": "5e685aa01e52b8c0abfc3854618deff97fc6d6107c54000475f9675b28ffffb4",
          "sha1": "c0f30c236239ed85c50322ead36803b391b6e780",
          "md5": "4c441d32d1239df42bc77d3a03bdb828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-neoforge-4.7.0-sources.jar",
          "url": "kfflang-neoforge-4.7.0-sources.jar",
          "size": 7128,
          "sha512": "b01dee444f6718dfc18aaaac25e8e9a265fc57fa619470a1a309a104c18222baf8e316720768ddb34d6428bf2fa3c0816c7ff5c15886b026b7eb8a6b152c9660",
          "sha256": "d0af5e250c9df56d10ab80d7d3f7b43e3430210b019a34e288a9fee561210007",
          "sha1": "d90cb07e60d948b83752b204d93297e63f5c968f",
          "md5": "486148e5dd5c7ad6a9ddabe179ca73f4"
        }
      ]
    }
  ]
}
