name: Release for 6.x

on:
  push:
    branches: [ '6.x' ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Which platform should the mod be published to?'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - curseforge
          - modrinth


jobs:
  curseforge:
    name: Publish release JAR on CurseForge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[Release]') || (inputs.platform == 'both' || inputs.platform == 'curseforge') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Upload to CurseForge
        run: ./gradlew publishCurseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  modrinth:
    name: Publish release JAR on Modrinth
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[Release]') || (inputs.platform == 'both' || inputs.platform == 'modrinth') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Upload to Modrinth
        run: ./gradlew publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
